In [40]:
import pandas as pd 

In [41]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [42]:
df = pd.DataFrame(data )

In [43]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [44]:
df.loc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [45]:
df.iloc[1:3]

name  salary            mail_id addr
1   krish     200   krish@ineuron.ai  blr
2  hitesh     300  hitesh@ineuron.ai  blr

In [46]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [47]:
df1 = pd.DataFrame(data1)

In [48]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [49]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [50]:
pd.concat([df,df1])

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [51]:
pd.concat([df,df1] , axis=1)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [52]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [53]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [54]:
df2 = pd.DataFrame(data2)

In [55]:
df3 = pd.DataFrame(data3)

In [56]:
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [57]:
df3

0     1      2           3
0    234   234  23543          ds
1     45   565  43543     bigdata
2  54465   767    454    web dev 
3    656  6778   5656  blockchian

In [58]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [59]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [60]:
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [62]:
df4 = pd.DataFrame(data4)

In [63]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [64]:
df5 = pd.DataFrame(data5)

In [65]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [70]:
pd.merge(df4,df5 ,  how ='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [67]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [68]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [71]:
pd.merge(df4,df5 ,  how ='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [72]:
pd.merge(df4, df5  , how = 'right' , on = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [75]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [76]:
df6 = pd.DataFrame(data6)

In [77]:
df7= pd.DataFrame(data7)

In [78]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [79]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [82]:
pd.merge(df6,df7 , left_on='emp_id1' , right_on='emp_id2',how = 'inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [95]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,123],
          'salary' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [96]:
df8 = pd.DataFrame(data8)

In [97]:
df9 = pd.DataFrame(data9)

In [98]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [99]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     123      43       234

In [100]:
pd.merge(df8,df9 , on = ['emp_id' , 'salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [112]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [113]:
df10 = pd.DataFrame(data10,index=['a' ,'b','c' ,'d'])

In [114]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [115]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [116]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [117]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [119]:
df_sales  = pd.read_csv("D:/sales_data_final.csv")

In [122]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [123]:
def profit_flag(a) : 
    if a >= 0 :
        return 'positive' 
    else :
        return 'negative'

In [124]:
profit_flag(-45)

'negative'

In [125]:
profit_flag(45)

'positive'

In [126]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [128]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [129]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [130]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [131]:
def quantity_flag(a) : 
    if  a < 10 :
        return 'low'
    elif a >10 and a <20 :
        return 'medium'
    else :
        return 'high'

In [132]:
df_sales['flag_quantity']= df_sales['quantity'].apply(quantity_flag)

In [133]:
df_sales.head(20)

order_id order_date ship_date       ship_mode      customer_name  \
0      AG-2011-2040   1/1/2011  1/6/2011  Standard Class    Toby Braunhardt   
1     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
2      HU-2011-1220   1/1/2011  1/5/2011    Second Class      Annie Thurman   
3   IT-2011-3647632   1/1/2011  1/5/2011    Second Class       Eugene Moren   
4     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
5     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
6      CA-2011-1510   1/2/2011  1/6/2011  Standard Class    Magdelene Morse   
7     IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
8     ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
9      IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   
10    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011  1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011  1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011  1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011  1/8/2011  Standard Class       Chris McAfee   

        segment              state         country  market          region  \
0      Consumer        Constantine         Algeria  Africa          Africa   
1      Consumer    New South Wales       Australia    APAC         Oceania   
2      Consumer           Budapest         Hungary    EMEA            EMEA   
3   Home Office          Stockholm          Sweden      EU           North   
4      Consumer    New South Wales       Australia    APAC         Oceania   
5      Consumer    New South Wales       Australia    APAC         Oceania   
6      Consumer            Ontario          Canada  Canada          Canada   
7     Corporate    New South Wales       Australia    APAC         Oceania   
8      Consumer           Auckland     New Zealand    APAC         Oceania   
9     Corporate             Ninawa            Iraq    EMEA            EMEA   
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   

    ... sales quantity discount    profit shipping_cost  order_priority  year  \
0   ...   408        2     0.00  106.1400         35.46          Medium  2011   
1   ...   120        3     0.10   36.0360          9.72          Medium  2011   
2   ...    66        4     0.00   29.6400          8.17            High  2011   
3   ...    45        3     0.50  -26.0550          4.82            High  2011   
4   ...   114        5     0.10   37.7700          4.70          Medium  2011   
5   ...    55        2     0.10   15.3420          1.80          Medium  2011   
6   ...   314        1     0.00    3.1200         24.10          Medium  2011   
7   ...   276        1     0.10  110.4120        125.32        C

In [134]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [135]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [136]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  

[5 rows x 25 columns]

In [137]:
import numpy as np 

In [138]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [139]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [140]:
np.array([[2,3,4] , [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [142]:
np.array([[1,2,3,4] , [ 2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [143]:
l = [[1,2,3,4] , [ 2,3,4,5]]

In [145]:
l[0][0]

1

In [152]:
a = np.array([3,4,5,6] , ndmin= 3)

In [153]:
a

array([[[3, 4, 5, 6]]])

In [154]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [155]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
arr.ndim

2

In [157]:
np.random.randint(1,10,(4,4))

array([[9, 8, 5, 6],
       [2, 7, 3, 3],
       [9, 3, 2, 3],
       [3, 3, 1, 1]])

In [158]:
np.random.randint(1,10,(4,4,2))

array([[[5, 2],
        [3, 3],
        [9, 4],
        [6, 4]],

       [[6, 6],
        [9, 4],
        [7, 2],
        [4, 2]],

       [[3, 3],
        [6, 9],
        [2, 8],
        [3, 3]],

       [[4, 4],
        [1, 3],
        [4, 6],
        [3, 6]]])

In [ ]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
 ## hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4 . Find out in this data that how many unique id's we have 
5 . which id is one of the active id that you have in whole dataset 
6 . how many of them have not logged there activity find out in terms of number of ids 
7 . Find out who is the laziest person id that we have in dataset 
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10 . who is the thired most active person in this dataset find out those in pandas and in sql both . 
11 . who is the 5th most laziest person avilable in dataset find it out 
12 . what is a totla acumulative calories burn for a person find out 


In [159]:
#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai 


SyntaxError: invalid syntax (2613182746.py, line 2)